# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        
    outputs:
      session-id: ${{ steps.start-session.outputs.session-id }}
      session-endpoint: ${{ steps.start-session.outputs.session-endpoint }}

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm install
    
    - uses: 721labs/hardhat-session-action@main
      id: start-session
      with:
        cmd: "npx hardhat test"
        # ID of session to resume; acquired through a previous output.
        # e.g. Started in same job, previous step: `${{ steps.previously-started-session.outputs.session-id }}`
        # e.g. Started in previous job: `${{ needs.test-action-new-session.outputs.session-id }}`
        # Type: String
        # Required: False
        session-id: "${{ steps.previously-started-session.outputs.session-id }}"
        # Directory containing your Hardhat project if it's not contained within root.
        # Note that the action does not read job.defaults.run.working_directory.
        # If `hardhat-directory` is set, it's unnecessary to pass `--config` within `cmd`.
        # Type: String
        # Required: False
        hardhat-directory: ""
